version: "2.0"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api-service
    ports:
      - "8080:8080"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client-service
    depends_on:
      - "api"
    ports:
      - "8081:8081"
